name: luxus_styling_salon
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.2.5
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/landingpage.jpeg
    - assets/img/client.jpeg
    - assets/img/contact.jpeg
    - assets/img/gallery_1.jpg
    - assets/img/gallery_2.jpg
    - assets/img/gallery_3.jpg
    - assets/img/gallery_4.jpg
    - assets/map_desktop.jpg
    - assets/map_mobile.jpg
    - assets/icons/tiktok.svg
    - assets/icons/instagram.svg

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald.ttf
