name: luxus_styling_salon
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/about.png

  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/static/Oswald-Bold.ttf
        - asset: fonts/static/Oswald-Medium.ttf
        - asset: fonts/static/Oswald-Regular.ttf
        - asset: fonts/static/Oswald-ExtraLight.ttf
        - asset: fonts/static/Oswald-Light.ttf
        - asset: fonts/static/Oswald-SemiBold.ttf
